---
available_weapons:
  - hkp2000
  - elite
  - p250
  - tec9
  - fn57
  - deagle
  - galilar
  - famas
  - ak47
  - m4a1_silencer
  - ssg08
  - aug
  - sg556
  - awp
  - scar20
  - g3sg1
  - nova
  - xm1014
  - mag7
  - m249
  - negev
  - mac10
  - mp9
  - mp7
  - ump45
  - p90
  - bizon
all_weapons:
  - glock
  - hkp2000
  - usp_silencer
  - elite
  - p250
  - tec9
  - fn57
  - deagle
  - galilar
  - famas
  - ak47
  - m4a1
  - m4a1_silencer
  - ssg08
  - aug
  - sg556
  - awp
  - scar20
  - g3sg1
  - nova
  - xm1014
  - mag7
  - m249
  - negev
  - mac10
  - mp9
  - mp7
  - ump45
  - p90
  - bizon
  - vest
  - vesthelm
  - taser
  - defuser
  - heavyarmor
  - molotov
  - incgrenade
  - decoy
  - flashbang
  - hegrenade
  - smokegrenade
  - tagrenade
